services:

  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD:-pass123}
      POSTGRES_USER: ${DATASOURCE_USERNAME:-user123}
      POSTGRES_DB: ${DATASOURCE_NAME:-db123}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: