services:

  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_DB: ${DATASOURCE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: usbtypec1/manashelper:${VERSION}
    container_name: app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - app_logs:/app/logs

volumes:
  postgres_data:
  app_logs:
