spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATASOURCE_NAME:db123}
    username: ${DATASOURCE_USERNAME:user123}
    password: ${DATASOURCE_PASSWORD:pass123}

crypto:
  secret-key: ${CRYPTO_SECRET_KEY:EBd1SJePRfSJkrxOu9f370kB9YFeQnvrT2eFKP8SEck=}
