spring:
  application:
    name: manashelper

  datasource:
    url: jdbc:postgresql://db:5432/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

crypto:
  secret-key: ${CRYPTO_SECRET_KEY}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

server:
  port: ${SERVER_PORT}
