"""add scheduled message deletions and food menu cleanup settings

Revision ID: d4e8a1f2c9b6
Revises: c1d4f8a2b6e7
Create Date: 2026-09-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e8a1f2c9b6'
down_revision: Union[str, Sequence[str], None] = 'c1d4f8a2b6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_menu_cleanup_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('delay_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('scheduled_message_deletions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_scheduled_message_deletions_delete_at', 'scheduled_message_deletions', ['delete_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_message_deletions_delete_at', table_name='scheduled_message_deletions')
    op.drop_table('scheduled_message_deletions')
    op.drop_table('food_menu_cleanup_settings')
    # ### end Alembic commands ###
