"""add obis credentials to users

Revision ID: e92bb795335a
Revises: 7d3a010eda82
Create Date: 2026-09-09 23:01:01.588626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92bb795335a'
down_revision: Union[str, Sequence[str], None] = '7d3a010eda82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('encrypted_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_password')
    op.drop_column('users', 'student_number')
    # ### end Alembic commands ###
