"""add notification settings

Revision ID: f3a1c9d5b8e2
Revises: e92bb795335a
Create Date: 2026-09-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a1c9d5b8e2'
down_revision: Union[str, Sequence[str], None] = 'e92bb795335a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_changes_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('before_lunch_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('before_dinner_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('exam_grades_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lesson_skips_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
